version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  test:
    build: .
    command: pytest
    depends_on:
      - db
    environment:
      DB_NAME: test_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      SPEECH_KEY: dummy_test_key
      SPEECH_REGION: dummy_test_region
