# Generated by Django 5.1.7 on 2025-03-29 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="user_id",
            new_name="user",
        ),
    ]
