# Generated by Django 5.1.7 on 2025-03-29 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("texts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passage",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="sentence",
            old_name="passage_id",
            new_name="passage",
        ),
    ]
