name: Build and Deploy

on:
  push:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: pera-be

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build with Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: '${{ env.REPO }}:test'
      - name: Run Pytest
        run: |
          docker run --rm \
            -e SPEECH_KEY='dummy_test_key' \
            -e SPEECH_REGION='dummy_test_region' \
            -e DB_NAME='test_db' \
            -e DB_USER='postgres' \
            -e DB_PASSWORD='postgres' \
            -e DB_HOST='host.docker.internal' \
            -e DB_PORT='5432' \
            ${{ env.REPO }}:test pytest

      - name: Build and push to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
      - name: Deploy to Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'