name: Build and Pytest

on:
  pull_request:

jobs:
  docker:
    name: Build and Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build with Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: '${{ env.REPO }}:test'
      - name: Run Pytest
        run: |
          docker run -e SPEECH_KEY='dummy_test_key' -e SPEECH_REGION='dummy_test_region' --rm ${{ env.REPO }}:test pytest
