name: Build and Pytest

on:
  pull_request:

jobs:
  docker:
    name: Build and Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build Docker images
        run: docker compose -p pera-be -f docker-compose.test.yml build
      - name: Run tests
        run: docker compose -p pera-be -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from test
      - name: Copy code coverage report from container
        run: docker cp pera-be-test-1:/app/coverage.xml .
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
