name: Build and Pytest

on:
  pull_request:

jobs:
  docker:
    name: Build and Pytest
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build with Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: '${{ env.REPO }}:test'
      - name: Run Pytest
        run: |
          docker run --rm \
            -e SPEECH_KEY='dummy_test_key' \
            -e SPEECH_REGION='dummy_test_region' \
            -e DB_NAME='test_db' \
            -e DB_USER='postgres' \
            -e DB_PASSWORD='postgres' \
            -e DB_HOST='host.docker.internal' \
            -e DB_PORT='5432' \
            ${{ env.REPO }}:test pytest
